/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectgames;

/**
 *
 * @author Aluno
 */
public class Bingo extends javax.swing.JFrame {

    /**
     * Creates new form Bingo
     */
    public Bingo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbvoltar2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbingo = new javax.swing.JTable();
        jbol1 = new javax.swing.JLabel();
        jbola1 = new javax.swing.JLabel();
        jbol4 = new javax.swing.JLabel();
        jbola4 = new javax.swing.JLabel();
        jbol2 = new javax.swing.JLabel();
        jbola2 = new javax.swing.JLabel();
        jbol3 = new javax.swing.JLabel();
        jbola3 = new javax.swing.JLabel();
        jbsortear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbvoltar2.setBackground(new java.awt.Color(235, 234, 234));
        jbvoltar2.setFont(new java.awt.Font("Aharoni", 1, 18)); // NOI18N
        jbvoltar2.setText("Voltar");
        jbvoltar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbvoltar2ActionPerformed(evt);
            }
        });
        getContentPane().add(jbvoltar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Bodoni MT Black", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Bingo");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 120, 60));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, -1));

        jtbingo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "B", "", "I", "", "N", "", "G", "", "O", ""
            }
        ));
        jScrollPane1.setViewportView(jtbingo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, 160));
        getContentPane().add(jbol1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, 40, 30));

        jbola1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bingos.jpg"))); // NOI18N
        getContentPane().add(jbola1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 60, 70));
        getContentPane().add(jbol4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 430, 40, 30));

        jbola4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bingos.jpg"))); // NOI18N
        getContentPane().add(jbola4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, 60, 70));
        getContentPane().add(jbol2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, 40, 30));

        jbola2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bingos.jpg"))); // NOI18N
        getContentPane().add(jbola2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 60, 70));
        getContentPane().add(jbol3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 40, 30));

        jbola3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bingos.jpg"))); // NOI18N
        getContentPane().add(jbola3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, 60, 70));

        jbsortear.setBackground(new java.awt.Color(0, 102, 102));
        jbsortear.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jbsortear.setForeground(new java.awt.Color(255, 255, 255));
        jbsortear.setText("Sortear");
        jbsortear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsortearActionPerformed(evt);
            }
        });
        getContentPane().add(jbsortear, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 80, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbvoltar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbvoltar2ActionPerformed
        MenuGames exec = new MenuGames();
        exec.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbvoltar2ActionPerformed

    private void jbsortearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsortearActionPerformed

        Random rd = new Random();
        int rad = rd.nextInt(3);
        palavra = Palavra[rad];

        for (x = 0; x < 8; x++) {

            tbpalavra.setValueAt("", 0, x);
        }

    }//GEN-LAST:event_jbsortearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bingo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bingo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bingo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bingo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bingo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jbol1;
    private javax.swing.JLabel jbol2;
    private javax.swing.JLabel jbol3;
    private javax.swing.JLabel jbol4;
    private javax.swing.JLabel jbola1;
    private javax.swing.JLabel jbola2;
    private javax.swing.JLabel jbola3;
    private javax.swing.JLabel jbola4;
    private javax.swing.JButton jbsortear;
    private javax.swing.JButton jbvoltar2;
    private javax.swing.JTable jtbingo;
    // End of variables declaration//GEN-END:variables
}
