/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectgames;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class Forca extends javax.swing.JFrame {

    String Palavra[] = {"cachorro", "gato", "coelho", "rato", "passaro", "peixe", "vegano", "humano", "macaco", "tamandua", "cobra", "lagarto", "capivara", "tigre", "ovelha", "boi", "vaca"};
    String Erradas[];
    int i;

    String palavra;
    int x = 0, c = 0, v = 0;

    public Forca() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbvoltar2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lbforca = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txletra = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jiniciar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbpalavra = new javax.swing.JTable();
        jlmensagem = new javax.swing.JLabel();
        jchutar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbvoltar2.setBackground(new java.awt.Color(235, 234, 234));
        jbvoltar2.setFont(new java.awt.Font("Aharoni", 1, 18)); // NOI18N
        jbvoltar2.setText("Voltar");
        jbvoltar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbvoltar2ActionPerformed(evt);
            }
        });
        getContentPane().add(jbvoltar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Bodoni MT Black", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Forca");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 120, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, -1));

        lbforca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forca1.png"))); // NOI18N
        jPanel1.add(lbforca, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 280, 330));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 51));
        jLabel2.setText("Palavra:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 80, 30));

        txletra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txletraActionPerformed(evt);
            }
        });
        jPanel1.add(txletra, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, 40, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Tema:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 60, 30));

        jTextField2.setText("ANIMAIS");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 210, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Letra:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 50, 30));

        jiniciar.setBackground(new java.awt.Color(0, 102, 102));
        jiniciar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jiniciar.setForeground(new java.awt.Color(255, 255, 255));
        jiniciar.setText("Iniciar");
        jiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jiniciarActionPerformed(evt);
            }
        });
        jPanel1.add(jiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 250, 80, 30));

        tbpalavra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", "", "", "", ""
            }
        ));
        jScrollPane1.setViewportView(tbpalavra);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 460, 30));
        jPanel1.add(jlmensagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 500, 470, 60));

        jchutar1.setBackground(new java.awt.Color(0, 102, 102));
        jchutar1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jchutar1.setForeground(new java.awt.Color(255, 255, 255));
        jchutar1.setText("Chutar");
        jchutar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchutar1ActionPerformed(evt);
            }
        });
        jPanel1.add(jchutar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, 80, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbvoltar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbvoltar2ActionPerformed
        MenuGames exec = new MenuGames();
        exec.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbvoltar2ActionPerformed

    private void txletraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txletraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txletraActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jiniciarActionPerformed

        Random rd = new Random();
        int rad = rd.nextInt(3);
        palavra = Palavra[rad];

        for (x = 0; x < 8; x++) {

            tbpalavra.setValueAt("", 0, x);
        }

      

    }//GEN-LAST:event_jiniciarActionPerformed

    private void jchutar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchutar1ActionPerformed

        String acerto = "n";

        for (x = 0; x < palavra.length(); x++) {

            // lbforca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/forca2.png")));
            //tbpalavra.setValueAt(null, 0, x);
            if (palavra.substring(x, x + 1).equals(txletra.getText())) {
                JOptionPane.showMessageDialog(null, "Acertou");
                tbpalavra.setValueAt(txletra.getText(), 0, x);
                v++;
                acerto = "s";
            }
        }
        if (v == palavra.length() || v == 8) {
            JOptionPane.showMessageDialog(null, "Parabens!");
            return;

        }
        if (acerto.equals("n")) {
            c++;
            if (c == 1) {
                lbforca.setIcon(new javax.swing.ImageIcon(getClass().getResource("forca2.png")));
            }
            if (c == 2) {
                lbforca.setIcon(new javax.swing.ImageIcon(getClass().getResource("forca3.png")));
            }
            if (c == 3) {
                lbforca.setIcon(new javax.swing.ImageIcon(getClass().getResource("forca4.png")));
            }
            if (c == 4) {
                lbforca.setIcon(new javax.swing.ImageIcon(getClass().getResource("forca5.png")));
            }
            if (c > 4) {
                lbforca.setIcon(new javax.swing.ImageIcon(getClass().getResource("forca6.png")));
                JOptionPane.showMessageDialog(null, "Perdeu o Jogo");
                return;
            }
        }

        txletra.setText("");
         txletra.requestFocus();

    }//GEN-LAST:event_jchutar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Forca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Forca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Forca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Forca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Forca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton jbvoltar2;
    private javax.swing.JButton jchutar1;
    private javax.swing.JButton jiniciar;
    private javax.swing.JLabel jlmensagem;
    private javax.swing.JLabel lbforca;
    private javax.swing.JTable tbpalavra;
    private javax.swing.JTextField txletra;
    // End of variables declaration//GEN-END:variables
}
